#!/usr/bin/env bash
#echo "
#===============
#|  Running detekt...
#===============
#"
#./gradlew --no-daemon --stacktrace -PdisablePreDex detekt
#
#detektStatus=$?
#
## return 1 exit code if running checks fails
#[ $detektStatus -ne 0 ] && exit 1

#echo "
#===================
#|  Formatting code with ktlintFormat...
#===================
#"
#./gradlew ktlintFormat

echo "
=========================
|  Running Lint Check...
=========================
"
./gradlew :app:lintDebug
#./gradlew --no-daemon --stacktrace -PdisablePreDex ktlintCheck


checkStyleStatus=$?

echo "
========================
|  End Lint Checking...
========================
"

# return 1 exit code if running checks fails
[ $checkStyleStatus -ne 0 ] && exit 1
exit 0
