#file: noinspection YAMLSchemaValidation
name: Android NC Build
on:
  pull_request:
    branches : [ main ]
    types: [opened, labeled]

jobs:
  pull_request:
    if: ${{ github.event.label.name == 'for review' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Gradlew Permissions
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: true

      - name: PR Comment
        uses: danger/kotlin@1.3.1
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}


