name: Android NC Build
on:
  pull_request:
    branches : [ main ]
    types: [opened, labeled]

jobs:
  pull_request:
    if: ${{ github.event.label.name == 'for review' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Gradlew Permissions
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt > lint-result.txt
        continue-on-error: true

      - name: Install reviewdog
        run: wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /tmp

      - name: Run reviewdog
        run: /tmp/reviewdog -f=checkstyle -f.diff.strip=0 -reporter=github-pr-review < lint-result.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
