#file: noinspection YAMLSchemaValidation
name: Android NC Build
on:
  pull_request:
    branches : [ main ]
    types: [opened, labeled]

jobs:
  pull_request:
    if: ${{ github.event.label.name == 'for review' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Gradlew Permissions
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: true
#
#      - name: PR Comment
#        uses: reviewdog/action-actionlint@42de1e3a0f52d5f8b8390894de87bc603844e530 # v1
#        with:
#          actionlint_flags: -ignore 'SC2086' -ignore 'SC2129'
#          fail_on_error: false
#          level: error
#          reporter: github-pr-review
#          filter_mode: file
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
#
      - name: PR Comment
        uses: danger/kotlin@1.3.1
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

#      - name: Detekt Lint
#        run: ./gradlew detekt > lint-result.txt
#        continue-on-error: true


#      - name: PR Comment
#        run: wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /tmp
#
#      - name: Run reviewdog
#        run: /tmp/reviewdog -f=detekt -f.diff.strip=0 -reporter=github-pr-review < app/build/reports/detekt/detekt.xml
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
