name: Merge Workflow
on:
  pull_request :
    types: [closed]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on : ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.2

      - name : Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Gradlew Permissions
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt